#!/bin/bash

activeWindow=$(xdotool getactivewindow)
xprop -id ${activeWindow} | grep "_NET_WM_STATE_ABOVE" >/dev/null 2>&1

# above
if [ "$?" == "0" ]
then
	wmctrl -r :ACTIVE: -b remove,above
else # no above
	wmctrl -r :ACTIVE: -b toggle,above
fi
