#!/bin/bash
if [ "$1" = "start" ]
then
	sh /home/si9ma/tomcat5/bin/startup.sh
elif [ "$1" = "stop" ]
then
    sh /home/si9ma/tomcat5/bin/shutdown.sh
elif [ "$1" = "restart" ]
then
    sh /home/si9ma/tomcat5/bin/shutdown.sh
	sh /home/si9ma/tomcat5/bin/startup.sh
else
	echo
	echo "usage:tomcat5 [start|stop|restart]"
	echo
fi
