#!/bin/bash
if [ "$1" = "start" ]
then
	sh /opt/tomcat/bin/startup.sh
elif [ "$1" = "stop" ]
then
	sh /opt/tomcat/bin/shutdown.sh
elif [ "$1" = "restart" ]
then
	sh /opt/tomcat/bin/shutdown.sh
	sh /opt/tomcat/bin/startup.sh
else
	echo
	echo "usage:tomcat [start|stop|restart]"
	echo
fi
