#!/bin/bash

x=$(xwininfo -id $(xdotool getactivewindow) | grep "Absolute upper-left X:" | tr -s " " |  cut -d " " -f 5)
y=$(xwininfo -id $(xdotool getactivewindow) | grep "Absolute upper-left Y:" | tr -s " " |  cut -d " " -f 5)

# terminaltor is special
ps $(xprop -id `xdotool getwindowfocus` | grep '_NET_WM_PID' | grep -oE '[[:digit:]]*$') | grep "/usr/bin/terminator"
if [ "$?" == "0" ]
then
	y=$[ $y - 18 ]
fi

# move up 20
y=$[ $y - $WINDOWMOVESTEP ]

# if < 0,set to 0
if [ "$y" -lt "0" ]
then
	y="0"
fi


# move
xdotool getactivewindow windowmove $x $y 
